# Generated by Django 4.1.3 on 2022-12-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_post_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
